// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGEEDPiPZUBMFBnojj1efwaSi3gs5ipeI',
    appId: '1:925798652962:web:d9d3271c20f04d94c13e7b',
    messagingSenderId: '925798652962',
    projectId: 'graduationproject-4394a',
    authDomain: 'graduationproject-4394a.firebaseapp.com',
    storageBucket: 'graduationproject-4394a.appspot.com',
    measurementId: 'G-RD0G1RJVVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMUg5ypXpfy5ASLz08VFREGWtG45Gf5s',
    appId: '1:925798652962:android:e56deaa94426dc77c13e7b',
    messagingSenderId: '925798652962',
    projectId: 'graduationproject-4394a',
    storageBucket: 'graduationproject-4394a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2XQROd1XqC-tB6AZ8eq-bDyWXFsnf0o',
    appId: '1:925798652962:ios:9ef69fb25875daa1c13e7b',
    messagingSenderId: '925798652962',
    projectId: 'graduationproject-4394a',
    storageBucket: 'graduationproject-4394a.appspot.com',
    iosClientId: '925798652962-qok7su5ojt4gm1euivlaqlvhce8n8ldp.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe2XQROd1XqC-tB6AZ8eq-bDyWXFsnf0o',
    appId: '1:925798652962:ios:9ef69fb25875daa1c13e7b',
    messagingSenderId: '925798652962',
    projectId: 'graduationproject-4394a',
    storageBucket: 'graduationproject-4394a.appspot.com',
    iosClientId: '925798652962-qok7su5ojt4gm1euivlaqlvhce8n8ldp.apps.googleusercontent.com',

    iosBundleId: 'com.example.graduationProject',
  );
}
