const Map<String, String> ar = {
  'Home': 'الصفحة الرئيسية',
  "Email": 'الايميل',
  "Password": 'الرقم السري',
  'Notification': 'الاشعارات',
  'Location': 'الموقع',
  'RTL': 'اللغة',
  "Change Language": 'تغيير اللغة',
  'Arabic': 'العربية',
  'English': 'الانجليزية',
  'Language': 'اللغة',
  'Light Theme': 'المظهر الفاتح',
  'Dark Theme': 'المظهر الداكن',
  'Settings': 'الاعدادات',
  'Log Out': 'تسجيل الخروج',
  'Quantity': 'الكمية',
  'Cart': 'العربة',
  'Privacy': 'الخصوصية',
  'Devices':'الأجهزة',
  'Drinking': 'الشرب',
  'Irrigration': 'الرى',
  'Kidney Patient': 'مريض الكلى',
  'User': 'المستخدم',
  'Admin': 'مسؤل',
  'Welcome Back': 'مرحبًا بعودتك',
  'Welcome Back!': '!مرحبًا بعودتك',
  'User Name': 'اسم االمستخدم',
  'Forget Your Password?': 'نسيت كلمة المرور؟',
  'SIGN IN': 'تسجيل الدخول',
  'or Social Media': 'أو وسائل التواصل الاجتماعي',
  'Id': 'هوية شخصية',
  'Welcome': 'مرحبًا',
  'Normal User': 'مستخدم عادي',
  'Farmer': 'مزارع',
  'SIGN UP': 'اشتراك',
  'id': 'هوية شخصية',
  'Welcome!': 'مرحبًا!',
  'Smart Sips app is used for monitoring the quality of your water to safe your heath from diseases.':
      'يستخدم تطبيق Smart Sips لمراقبة جودة المياه الخاصة بك لحماية صحتك من الأمراض.',
  'choose one for next step': 'اختر واحدة للخطوة التالية',
   'Type your message..':'اكتب رسالتك ..',
   'Chat':'دردشة',

};
