const Map<String, String> en = {
  'Home': 'Home',
  "Email": 'Email',
  "Password": 'Password',
  'Notification': 'Notification',
  'Location': 'Location',
  'RTL': 'RTL',
  "Change Language": 'Change Language',
  'Arabic': 'Arabic',
  'English': 'English',
  'Language': 'Language',
  'Light Theme': 'Light Theme',
  'Dark Theme': 'Dark Theme',
  'Settings': 'Settings',
  'Log Out': 'Log Out',
  'Privacy': 'Privacy',
  'Devices':'Devices',
  'Drinking': 'Drinking',
  'Irrigration': 'Irrigration',
  'Kidney Patient': 'Kidney Patient',
  'User': 'User',
  'Admin': 'Admin',
  'Welcome Back': 'Welcome Back',
  'Welcome Back!': 'Welcome Back!',
  'User Name': 'User Name',
  'Forget Your Password?': 'Forget Your Password?',
  'SIGN IN': 'SIGN IN',
  'or Social Media': 'or Social Media',
  'Id': 'Id',
  'Welcome': 'Welcome',
  'Normal User': 'Normal User',
  'Farmer': 'Farmer',
  'SIGN UP': 'SIGN UP',
  'id': 'id',
  'Welcome!': 'Welcome!',
  'Smart Sips app is used for monitoring the quality of your water to safe your heath from diseases.':
      'Smart Sips app is used for monitoring the quality of your water to safe your heath from diseases.',
  'choose one for next step': 'choose one for next step',
  'Type your message..':'Type your message..',
  'Chat':'Chat',

};
